---
- name: Become block
  become: true
  block:
#    - name: Set Ansible Python interpreter to k8s virtualenv
#      ansible.builtin.set_fact:
#        ansible_python_interpreter: /usr/libexec/platform-python

    - name: Pull images for student
      become_user: "{{ lb1344_student_user }}"
      containers.podman.podman_image:
        name: "{{ item.name }}"
        pull: true
        tag: "{{ item.tag }}"
      loop: "{{ lb1344_images }}"  

#    - name: Set Ansible Python interpreter to k8s virtualenv
#      ansible.builtin.set_fact:
#        ansible_python_interpreter: /opt/virtualenvs/k8s/bin/python